name = "Giovani Cooperatori Trentini"
description = "Associazione giovanile del movimento cooperativo trentino"
keywords = "giovani, cooperatori, trentini, cooperazione, trentino"
image = "logo_color_trans_hiq.png"
theme = "light"
primary_color = "#043c49"
text_align = "center"
gtag_id = ""
base_url = "https://giovanicooperatoritrentini.github.io/"

[[sections]]
title = "Collegamenti"
description = ""
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Assemblea 2024"
description = "Iscriviti alla nostra assemblea / 6 aprile 2024"
url = "https://www.imdb.com/title/tt2872718/"
[[sections.items]]
title = "Diventa socio"
description = "Diventa socio dei Giovani Cooperatori Trentini"
url = "https://www.imdb.com/title/tt2872718/"
[[sections.items]]
title = "Sito internet"
description = "A groundbreaking romantic drama challenging societal expectations"
url = "https://www.imdb.com/title/tt0388795/"
[[sections.items]]
title = "Statuto"
description = "Statuto dell'associazione - aggiornamento 2023"
url = "https://www.imdb.com/title/tt1392214/"
[[sections.items]]
title = "Bilanci"
description = "Consulta i bilanci d'esercizio"
url = "https://www.imdb.com/title/tt1392214/"

[[sections]]
title = "Links"
description = "Seguici sui nostri social"
direction = "row"
item_style = "filled"
[[sections.items]]
title = "Instagram"
url = "https://www.instagram.com/giovanicooperatoritrentini"
[[sections.items]]
title = "Email"
url = "mailto:giovanicooperatoritrentini@gmail.com"

